netty:
  client:
    tcp:
      enabled: true
      host: 127.0.0.1
      port: 8081
    udp:
      enabled: true
      host: 127.0.0.1
      port: 8082
    websocket:
      enabled: true
      host: 127.0.0.1
      port: 8083